<?php

/**
 * Implements hook_ctools_plugin_directory().
 * This lets ctools know to scan my module for a content_type plugin file
 * Detailed docks in ctools/ctools.api.php
 */
function entity_locator_ctools_plugin_directory($owner, $plugin) {
  // we'll be nice and limit scandir() calls
  if ($owner == 'ctools' && !empty($plugin)) {
    return "plugins/$plugin";
  }
}

/**
 * Implements hook_menu().
 */
function entity_locator_menu() {
  $items['admin/config/search/entity-locator'] = array(
    'access arguments' => array('administer site configuration'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('entity_locator_config'),
    'title' => 'Entity Locator',
    'file' => 'entity_locator.pages.inc',
  );

  $items['entity_locator/ajax/entities/%'] = array(
    'type' => MENU_CALLBACK,
    'page callback' => 'entity_locator_ajax',
    'page arguments' => array(3),
    'access callback' => TRUE,
  );

  return $items;
}

function entity_locator_ajax($bundle) {
  $markers = array();

  // @todo Use config
  $entity_locator = new EntityLocator($bundle);
  $entities = $entity_locator->get_entities();

  foreach ($entities as $nid => $entity) {
    if ($entity->location && $entity->location['lid'] != NULL) {
      $markers[] = array(
        'title' => $entity->title,
        'lat' => $entity->location['latitude'],
        'lng' => $entity->location['longitude'],
      );
    }
  }

  // @todo Remove this. Just a test.
  $markers[] = array(
    'lat' => '67.56109365945179',
    'lng' => '-75.8935546875',
    'title' => 'Hello World',
  );

  return drupal_json_output($markers);
}

/**
 * Implements hook_theme().
 */
function entity_locator_theme() {
  $templates = array();
  $templates['entity_locator_preview'] = array(
    'template' => 'entity_locator_preview',
  );
  $templates['entity_locator'] = array(
    'template' => 'entity_locator',
  );
  return $templates;
}
